import json
import requests

def load_stash_report(filename="stash_report.json"):
    """Loads the JSON file generated by your slot grid scanner."""
    try:
        with open(filename, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"[-] Could not find '{filename}'. Make sure your scanner script has run successfully.")
        return None

def calculate_net_worth():
    stash = load_stash_report()
    if not stash:
        return

    print("[*] Fetching live PoE2 economy rates from poe.ninja...")
    url = "https://poe.ninja/poe2/api/economy/exchange/current/overview?league=Runes%20of%20Aldur&type=Currency"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ExileVision/1.0'}
    
    try:
        response = requests.get(url, headers=headers)
        if response.status_code != 200:
            print(f"[-] Failed to fetch prices. HTTP Status: {response.status_code}")
            return
            
        data = response.json()
        lines = data.get('lines', [])
        rates = data.get('rates', {})
        
        # Establish our conversion rates directly from the poe.ninja base metadata
        chaos_per_divine = float(rates.get("chaos", 7.11))
        
        # Build a market dictionary indexing the base "divine" value for every item id
        market_prices_divine = {}
        for line in lines:
            item_id = line.get('id')
            primary_value = line.get('primaryValue', 0.0)
            if item_id:
                market_prices_divine[item_id] = float(primary_value)
        
        # -----------------------------------------------------------------
        # FIX: Normalize the item names & lock down baseline anchor values
        # -----------------------------------------------------------------
        # 1 Divine is always exactly 1 Divine
        market_prices_divine["divine"] = 1.0
        market_prices_divine["divine-orb"] = 1.0
        
        # 1 Chaos is mathematically exactly (1 / chaos_per_divine) Divines
        market_prices_divine["chaos"] = 1.0 / chaos_per_divine
        market_prices_divine["chaos-orb"] = 1.0 / chaos_per_divine

        # Map typical poe.ninja API ids to your stash scanner's full string keys
        api_key_mapping = {
            # Standard mappings
            "exalted-orb": "exalted",
            "vaal-orb": "vaal",
            "greater-exalted-orb": "greater-exalted-orb",
            "greater-chaos-orb": "greater-chaos-orb",
            
            # Shifting the "orb-of" syntax to match poe.ninja's internal database keys
            "orb-of-alchemy": "alchemy", 
            "orb-of-annulment": "annulment",
            "orb-of-chance": "chance",
            "regal-orb": "regal",
            
            # Base tier bulk mappings
            "orb-of-transmutation": "transmutation",
            "orb-of-augmentation": "augmentation",
            
            # Just in case the API uses the reverse naming scheme for lower tiers:
            "orb-of-transmutation": "transmutation-orb",
            "orb-of-augmentation": "augmentation-orb",
        }
        
        total_divines = 0.0
        items_value_list = []
        
        for item_key, count in stash.items():
            if count == 0:
                continue
            
            # Find the true internal name poe.ninja uses for this currency item
            ninja_lookup_key = api_key_mapping.get(item_key, item_key)
            
            # Extract price in Divines
            unit_price_divine = market_prices_divine.get(ninja_lookup_key, 0.0)
            
            # Calculate item worth in Divines
            item_total_divines = count * unit_price_divine
            total_divines += item_total_divines
            
            # Pre-calculate the exact values for Chaos
            unit_price_chaos = unit_price_divine * chaos_per_divine
            item_total_chaos = item_total_divines * chaos_per_divine
            
            items_value_list.append({
                "id": item_key,
                "count": count,
                "price_div": unit_price_divine,
                "total_div": item_total_divines,
                "price_chaos": unit_price_chaos,
                "total_chaos": item_total_chaos
            })
            
        total_chaos = total_divines * chaos_per_divine

        # =================================================================
        # PREVIEW: CHAOS-FOCUSED VIEW
        # =================================================================
        print("\n" + "="*70)
        print(f"{'STASH CURRENCY BREAKDOWN (CHAOS VIEW)':^70}")
        print("="*70)
        print(f"{'Item ID':<32} | {'Qty':<5} | {'Unit Price':<12} | {'Total Chaos':<12}")
        print("-" * 70)
        
        items_value_list.sort(key=lambda x: x['total_chaos'], reverse=True)
        for item in items_value_list:
            print(f"{item['id']:<32} | {item['count']:<5} | {item['price_chaos']:>10.4f}c | {item['total_chaos']:>10.1f}c")
        
        print("-" * 70)
        print(f"💰 Total Net Worth: {total_chaos:,.1f} c")
        print("="*70 + "\n")

        # =================================================================
        # PREVIEW: DIVINE-FOCUSED VIEW
        # =================================================================
        print("="*70)
        print(f"{'STASH CURRENCY BREAKDOWN (DIVINE VIEW)':^70}")
        print("="*70)
        print(f"{'Item ID':<32} | {'Qty':<5} | {'Unit Price':<12} | {'Total Divine':<12}")
        print("-" * 70)
        
        items_value_list.sort(key=lambda x: x['total_div'], reverse=True)
        for item in items_value_list:
            print(f"{item['id']:<32} | {item['count']:<5} | {item['price_div']:>10.5f}d | {item['total_div']:>10.3f}d")
        
        print("-" * 70)
        print(f"✨ Total Net Worth: {total_divines:,.2f} div  (1 div = {chaos_per_divine:.2f}c)")
        print("="*70 + "\n")

    except Exception as e:
        print(f"[-] Error compiling wealth report: {str(e)}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    calculate_net_worth()